import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowRight,Check,ChevronDown,Clock3,Droplets,Menu,ShieldCheck,Sparkles,Star,Users,X}from'lucide-react';import'./styles.css';

const wa='https://wa.me/5511914368178?text=Olá!%20Quero%20solicitar%20um%20orçamento.';
const services=[['Limpeza de estofados','Higienização profunda para sofás, poltronas e cadeiras.','🛋️'],['Limpeza de colchões','Mais saúde e bem-estar para suas noites de sono.','▰'],['Limpeza de tapetes','Cuidado especializado que remove sujeiras e odores.','◌'],['Impermeabilização','Proteção prolongada contra líquidos e manchas.','◈']];
function App(){const[open,setOpen]=useState(false);const[ready,setReady]=useState(false);useEffect(()=>{setReady(true)},[]);return <div className="site"><header><a className="brand" href="#inicio"><img src="/logo.png"/><span>Colors<span>Clean</span></span></a><button className="menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'show':''}>{['Serviços','Diferenciais','Como funciona','Resultados','Contato'].map(x=><a key={x} href={'#'+x.toLowerCase().replace(' ','-')} onClick={()=>setOpen(false)}>{x}</a>)}<a className="nav-cta" href={wa}>Falar no WhatsApp <ArrowRight size={16}/></a></nav></header><main>
<section id="inicio" className={'hero '+(ready?'in':'')}><div className="hero-glow"/><div className="hero-copy"><p className="eyebrow">LIMPEZA & IMPERMEABILIZAÇÃO <i/></p><h1>Mais vida e proteção<br/>para o que <em>você ama.</em></h1><p className="lead">Limpeza profissional de estofados e impermeabilização para deixar sua casa mais saudável, bonita e protegida.</p><div className="actions"><a className="primary" href={wa}>Solicitar orçamento <ArrowRight size={18}/></a><a className="secondary" href="#serviços">Conheça nossos serviços <ArrowRight size={18}/></a></div><div className="trust"><span><ShieldCheck/> Atendimento cuidadoso</span><span><Droplets/> Produtos seguros</span><span><Sparkles/> Resultado visível</span></div></div><div className="hero-card"><span>Ambientes mais limpos,<br/><b>momentos mais leves.</b></span><div className="orb">✦</div></div></section>
<section className="strip"><span><Check/> Equipe especializada</span><span><Check/> Orçamento rápido</span><span><Check/> Atendimento em São Paulo</span><span><Check/> Cuidado em cada detalhe</span></section>
<section id="serviços" className="section"><div className="section-head"><div><p className="eyebrow">NOSSOS SERVIÇOS <i/></p><h2>Uma solução completa para o seu ambiente.</h2></div><a href={wa}>Fale com a equipe <ArrowRight size={16}/></a></div><div className="service-grid">{services.map(([t,d,icon])=><article className="service" key={t}><div className="service-image"><span>{icon}</span></div><div><h3>{t}</h3><p>{d}</p><a href={wa}>Saiba mais <ArrowRight size={15}/></a></div></article>)}</div></section>
<section id="diferenciais" className="dark-section"><div className="feature-intro"><p className="eyebrow">POR QUE ESCOLHER A COLORSCLEAN? <i/></p><h2>Muito mais que limpeza.<br/><em>Cuidado em cada detalhe.</em></h2></div><div className="features">{[['Qualidade comprovada','Um cuidado pensado para o seu espaço.'],['Atendimento personalizado','A solução certa para cada necessidade.'],['Agilidade no serviço','Seu tempo também importa.'],['Produtos seguros','Mais tranquilidade para sua família.']].map(([a,b],i)=><div className="feature" key={a}><div className="feature-icon">{[<Star/>,<Users/>,<Clock3/>,<ShieldCheck/>][i]}</div><h3>{a}</h3><p>{b}</p></div>)}</div></section>
<section id="como-funciona" className="section steps"><p className="eyebrow">COMO FUNCIONA <i/></p><h2>Do primeiro contato ao resultado final.</h2><div className="step-grid">{[['01','Você chama','Conte o que precisa pelo WhatsApp.'],['02','A gente entende','Conversamos sobre o ambiente e o melhor cuidado.'],['03','Cuidamos de tudo','Nossa equipe realiza o serviço com atenção.'],['04','Você aproveita','Mais conforto, limpeza e proteção para sua rotina.']].map(([n,t,d])=><div className="step" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section id="resultados" className="result"><div><p className="eyebrow">UM NOVO JEITO DE CUIDAR <i/></p><h2>A diferença aparece<br/><em>nos detalhes.</em></h2><p>Seu estofado merece mais do que uma limpeza rápida. Conte com um atendimento cuidadoso para renovar o ambiente e prolongar a vida útil dos seus tecidos.</p><a className="primary" href={wa}>Quero meu orçamento <ArrowRight size={18}/></a></div><div className="result-visual"><div className="before">ANTES</div><div className="after">DEPOIS</div><div className="divider"/></div></section>
<section id="contato" className="final"><p className="eyebrow">VAMOS CONVERSAR? <i/></p><h2>Seu conforto começa<br/>com um <em>cuidado melhor.</em></h2><p>Fale com a ColorsClean e descubra a melhor solução para sua casa ou negócio.</p><a className="primary" href={wa}>Falar no WhatsApp <ArrowRight size={18}/></a></section></main><footer><div className="brand"><img src="/logo.png"/><span>Colors<span>Clean</span></span></div><div><b>ColorsClean</b><p>Limpeza e impermeabilização<br/>para ambientes mais seguros.</p></div><div><b>Contato</b><p>(11) 91436-8178<br/>São Paulo e região</p></div><small>© 2026 ColorsClean. Todos os direitos reservados.</small></footer></div>}
createRoot(document.getElementById('root')!).render(<App/>);
